// my array with objects
//Each object has a `name` and an `img` property specifying the name and image source of the card.

const memoryCards = [
  {
    name: 'earth',
    img: 'images/earth_IMG.jpeg'
  },
  {
    name: 'saturn',
    img: 'images/saturn_IMG.jpeg'
  },
  {
    name: 'astronaut',
    img: 'images/astronaut_IMG.jpeg'
  },
  {
    name: 'jupiter',
    img: 'images/jupiter_IMG.jpeg'
  },
  {
    name: 'nasa',
    img: 'images/nasa_IMG.png'
  },
  {
    name: 'moon',
    img: 'images/moon_IMG.webp'
  },
  {
    name: 'earth',
    img: 'images/earth_IMG.jpeg'
  },
  {
    name: 'saturn',
    img: 'images/saturn_IMG.jpeg'
  },
  {
    name: 'astronaut',
    img: 'images/astronaut_IMG.jpeg'
  },
  {
    name: 'jupiter',
    img: 'images/jupiter_IMG.jpeg'
  },
  {
    name: 'nasa',
    img: 'images/nasa_IMG.png'
  },
  {
    name: 'moon',
    img: 'images/moon_IMG.webp'
  }
]

// 'memoryCards' array is sorted w/ sort method and comparison function

// comparison function randomly shuffles elements in array by subtracting a random value b/w 0 and 1 (generated by 'Math.random()')

memoryCards.sort(() => 0.5 - Math.random()) //shortcut to randomize array

//variables referenced to HTML elements 'container' and 'result'
const containerVisual = document.querySelector('#container')
const resultVisual = document.querySelector('#result')

//declared empty arrays
//keeps track of cards clicked by user, their corresponding IDs, and card matches
let cardsClicked = []
let cardsClickedIds = []
const cardsWon = []

//function used to create the HTML representation of game
//loops through the `memoryCards` array and creates `<img>` elements for each card

//created elements are assigned the 'images/space_IMG.jpeg' image source, a `data-id` attribute corresponding to the index of the card in the array, and an event listener for the 'click' event that invokes the `flipCard()` function

buildBoard()

function buildBoard() {
  for (let i = 0; i < memoryCards.length; i++) {
    const card = document.createElement('img')
    card.setAttribute('src', 'images/space_IMG.jpeg')
    card.setAttribute('data-id', i)
    card.addEventListener('click', flipCard)
    containerVisual.appendChild(card)
  }
}

function seeMatch() {
  const cards = document.querySelectorAll('img')
  const selectOneId = cardsClickedIds[0]
  const selectTwoId = cardsClickedIds[1]

  console.log('check for match!')
  if (selectOneId == selectTwoId) {
    cards[selectOneId].setAttribute('src', 'images/space_IMG.jpeg')
    cards[selectTwoId].setAttribute('src', 'images/space_IMG.jpeg')
    alert('You have clicked the same image!')
  }
  if (cardsClicked[0] == cardsClicked[1]) {
    alert('Interstellar Match!')

    cards[selectOneId].setAttribute('src', 'images/blank_IMG.png')
    cards[selectTwoId].setAttribute('src', 'images/blank_IMG.png')
    cards[selectOneId].removeEventListener('click', flipCard)
    cards[selectTwoId].removeEventListener('click', flipCard)
    cardsWon.push(cardsClicked)
  } else {
    cards[selectOneId].setAttribute('src', 'images/space_IMG.jpeg')
    cards[selectTwoId].setAttribute('src', 'images/space_IMG.jpeg')
    alert('Lost In Space Try Again!')
  }
  resultVisual.textContent = cardsWon.length
  cardsClicked = []
  cardsClickedIds = []

  if (cardsWon.length == memoryCards.length / 2) {
    // alert('Win! Returning to Earth')
    resultVisual.textContent = 'Congratulations Returning to Earth!'
  }
}

function flipCard() {
  const cardId = this.getAttribute('data-id') //this key allows to interact with clicked img
  cardsClicked.push(memoryCards[cardId].name)
  cardsClickedIds.push(cardId)
  this.setAttribute('src', memoryCards[cardId].img)
  if (cardsClicked.length === 2) {
    setTimeout(seeMatch, 500)
  }
}
function resetBoard() {
  cardsClicked = []
  cardsClickedIds = []
  cardsWon.length = 0
  resultVisual.textContent = 0
  containerVisual.innerHTML = ''
  buildBoard()
}

const resetButton = document.querySelector('#resetButton')
resetButton.addEventListener('click', resetBoard)
